version: "3.8"
services:
  postgres:
    image: "postgres"
    container_name: postgres
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=seu_banco
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@dominio.com"
      PGADMIN_DEFAULT_PASSWORD: "sua_senha_pgadmin"
    ports:
      - "54321:80"
    depends_on:
      - postgres